#!/usr/bin/env python

"""The setup script."""

from setuptools import setup, find_packages

requirements = [
    "click==7.1.2",
    "pandas==1.2",
    "pytest==6.2.1",
    "tox==3.21.2",
    "genotype-variants==0.3.1",
]

setup_requirements = [
    "click==7.1.2",
    "pandas==1.2",
    "genotype-variants==0.3.1",
]

test_requirements = [
    "pytest==6.2.1",
    "tox==3.21.2",
]

setup(
    author="msk-access",
    author_email="rons.shah@gmail.com",
    python_requires=">=3.7",
    classifiers=[
        "Development Status :: 2 - Pre-Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: Apache Software License",
        "Natural Language :: English",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
    ],
    description="Package for downstream analysis  of results generated by ACCESS workflows",
    entry_points={
        "console_scripts": [
            "spectrum=spectrum.cli:main",
        ],
    },
    install_requires=requirements,
    license="Apache Software License 2.0",
    long_description="Generate the comprehensive results across multiple samples from a single patient",
    include_package_data=True,
    keywords="spectrum",
    name="spectrum",
    packages=find_packages(include=["spectrum", "spectrum.*"]),
    setup_requires=setup_requirements,
    test_suite="tests",
    tests_require=test_requirements,
    url="https://github.com/rhshah/spectrum",
    version="0.1.0",
    zip_safe=False,
)
